/**
 * LHR Shed Codes — Heathrow cargo shed lookup library
 *
 * Data source:
 *   - data/lhr-sheds-merged.json  (generated by scripts/merge-lhr-sheds.mjs)
 *     Combines FreightUtils operational data (maintained by Marius Cristoiu)
 *     with HMRC Appendix 16D (ITSF) and 16F (ETSF) regulated registrations.
 *
 * Confidence tiers:
 *   - verified:              operational + HMRC both present, consistent
 *   - community_contributed: email sourced from industry peer (CIS_AMI)
 *   - pending_verification:  operational record flagged partial / verify_on_shift
 *                            / uncertain HMRC mapping
 *   - operational_only:      operational data only (incl. HMRC-deregistered AAS)
 *   - hmrc_only:             HMRC-registered LHR location w/o operational record
 */

import raw from '@/data/lhr-sheds-merged.json';

// ─── Types ──────────────────────────────────────────────────────────

export type Confidence =
  | 'verified'
  | 'community_contributed'
  | 'pending_verification'
  | 'operational_only'
  | 'hmrc_only';

export interface AirlineRef {
  code: string;
  name: string;
  awb_prefix?: string;
  variant?: string;
  verify?: string;
}

export interface HmrcBlock {
  code: string | null;
  status: string;
  source?: 'itsf' | 'etsf';
  legal_name?: string;
  address?: string;
  decomposed?: {
    country: string;
    prefix: string;
    office: string;
    airport: string;
    suffix: string;
    suffix_length: number;
  };
  registered_date?: string;
  deregistered_date?: string;
  note?: string;
}

export interface MergedShed {
  key: string;
  shed_code: string | null;
  subject_code: string | null;
  handler_legal_name: string | null;
  handler_common_name: string | null;
  prealert_email: string | null;
  airlines: AirlineRef[];
  awb_prefixes: string[];
  routing_notes: string | null;
  is_critical_rule: boolean;
  operational_status: string | null;
  hmrc: HmrcBlock;
  confidence: Confidence;
  last_verified: string | null;
  source: 'operational' | 'hmrc';
}

export interface CriticalRules {
  horseshoe_default: {
    sheds_covered: string[];
    subject_code: string;
    prealert_email: string;
    description: string;
    hmrc_registration: string;
  };
  horseshoe_aa_exception: {
    airline: string;
    awb_prefix: string;
    physical_shed: string;
    subject_code: string;
    prealert_email: string;
    description: string;
    hmrc_registration: string;
  };
  grey_area_gf_ul_vn_2c_sv: { note: string };
}

export interface AirlinePrefixOverride {
  airline_code: string;
  airline_name: string;
  shed_common_name: string;
  shed_code: string;
  subject_code: string;
  prealert_email: string;
  note?: string;
}

export interface MergedLhrData {
  _meta: {
    generated_at: string;
    primary_airport: 'LHR';
    total_sheds: number;
    operational_source_version: string | null;
    operational_last_verified: string | null;
    hmrc_sources: {
      itsf: { fetched_at: string; total_records: number; lhr_related: number; source_url: string };
      etsf: { fetched_at: string; total_records: number; lhr_related: number; source_url: string };
    };
    confidence_distribution: Record<string, number>;
    licence: string;
    corrections_email: string;
  };
  critical_rules: CriticalRules;
  airline_prefix_overrides: Record<string, AirlinePrefixOverride>;
  sheds: MergedShed[];
  other_airports: Array<{
    key: string;
    airport: string;
    shed_code: string | null;
    subject_code: string | null;
    handler_legal_name: string | null;
    handler_common_name: string | null;
    prealert_email: string | null;
    routing_notes: string | null;
    last_verified: string | null;
  }>;
  questions_for_soap_on_shift: string[];
}

// ─── Data singleton ─────────────────────────────────────────────────

/**
 * Read-time redaction layer.
 *
 * The merged JSON (`data/lhr-sheds-merged.json`) is generated by the merge
 * script from `data/operational-context-lhr.json` + HMRC source JSONs.
 * Curation edits that landed in the operational JSON will only propagate
 * to the merged JSON when the merge script is re-run. Until that happens,
 * we apply the same text normalisations here so the public surface is
 * consistent.
 *
 * Two concerns:
 *   1. `_meta.corrections_email` → `contact@freightutils.com` (business
 *      inbox, not the maintainer's personal address).
 *   2. Scrub third-party forwarder (ex-employer) name from AA-exception
 *      narrative notes — the operational-truth claim stands; the specific
 *      attribution of who-failed-to-update-what does not belong on the
 *      public surface without that party's consent.
 *
 * We deliberately do NOT touch:
 *   - HMRC regulated register entries (public-record truth about HMRC-
 *     registered facilities), including handler_legal_name / hmrc.legal_name
 *     fields sourced from the HMRC ITSF/ETSF datasets.
 *   - Structural fields (codes, keys, airlines, prefixes).
 */

const CEVA_REDACTION_RULES: Array<[RegExp, string]> = [
  [
    /CEVA never updated AA's prealert subject\/email\./g,
    "AA's prealert subject/email were never updated to reflect the relocation.",
  ],
  [
    /CEVA never updated AA's prealert subject\/email/g,
    "AA's prealert subject/email were never updated",
  ],
  [
    /Operationally still in active use by CEVA and other forwarders/g,
    'Operationally still in active use industry-wide',
  ],
  [
    /CEVA PDF originally routed/g,
    'Historical handler routing documentation originally assigned',
  ],
  [
    /remains in active operational use at CEVA and industry-wide/g,
    'remains in active operational use industry-wide',
  ],
  [
    /, CEVA Heathrow → WFS Heathrow from 7 May 2026/g,
    '',
  ],
];

function scrubCevaText(input: string): string {
  let out = input;
  for (const [pattern, replacement] of CEVA_REDACTION_RULES) {
    out = out.replace(pattern, replacement);
  }
  return out;
}

function scrubStringFieldsOnObject<T extends Record<string, unknown>>(obj: T): T {
  const next: Record<string, unknown> = { ...obj };
  for (const key of Object.keys(next)) {
    const v = next[key];
    if (typeof v === 'string') next[key] = scrubCevaText(v);
  }
  return next as T;
}

function redactMerged(data: MergedLhrData): MergedLhrData {
  const next: MergedLhrData = {
    ...data,
    _meta: {
      ...data._meta,
      corrections_email: 'contact@freightutils.com',
    },
    critical_rules: {
      horseshoe_default: { ...data.critical_rules.horseshoe_default },
      horseshoe_aa_exception: scrubStringFieldsOnObject(
        data.critical_rules.horseshoe_aa_exception,
      ),
      grey_area_gf_ul_vn_2c_sv: scrubStringFieldsOnObject(
        data.critical_rules.grey_area_gf_ul_vn_2c_sv,
      ),
    },
    sheds: data.sheds.map(s => {
      const next: MergedShed = { ...s };
      if (typeof next.routing_notes === 'string') {
        next.routing_notes = scrubCevaText(next.routing_notes);
      }
      if (next.hmrc && typeof next.hmrc === 'object') {
        const hmrc = { ...next.hmrc };
        if (typeof hmrc.note === 'string') hmrc.note = scrubCevaText(hmrc.note);
        next.hmrc = hmrc;
      }
      return next;
    }),
  };
  return next;
}

const DATA: MergedLhrData = redactMerged(raw as unknown as MergedLhrData);

export const SHED_COUNT = DATA.sheds.length;
export const OPERATIONAL_COUNT = DATA.sheds.filter(s => s.source === 'operational').length;
export const HMRC_COUNT = DATA.sheds.filter(s => s.source === 'hmrc').length;
export const CONFIDENCE_COUNTS = DATA._meta.confidence_distribution;
export const LAST_VERIFIED = DATA._meta.operational_last_verified;

// ─── Accessors ──────────────────────────────────────────────────────

export function getMeta() {
  return DATA._meta;
}

export function getCriticalRules(): CriticalRules {
  return DATA.critical_rules;
}

export function getAirlinePrefixOverrides(): Record<string, AirlinePrefixOverride> {
  return DATA.airline_prefix_overrides;
}

export function getAllSheds(): MergedShed[] {
  return DATA.sheds;
}

export function getQuestions(): string[] {
  return DATA.questions_for_soap_on_shift;
}

// ─── Lookups ────────────────────────────────────────────────────────

/**
 * Find a shed by either operational key (e.g. "CIS_AMI") or shed_code ("CIS").
 * Case-insensitive.
 */
export function findByKeyOrCode(code: string): MergedShed[] {
  const needle = code.trim().toUpperCase();
  if (!needle) return [];
  return DATA.sheds.filter(
    s => s.key.toUpperCase() === needle || (s.shed_code || '').toUpperCase() === needle,
  );
}

/**
 * Find sheds by HMRC location code, e.g. "GBAULHRLHRACS".
 */
export function findByHmrcCode(hmrcCode: string): MergedShed | null {
  const needle = hmrcCode.trim().toUpperCase();
  if (!needle) return null;
  return (
    DATA.sheds.find(
      s => s.hmrc?.code && s.hmrc.code.toUpperCase() === needle,
    ) || null
  );
}

/**
 * Find sheds handling a specific airline (by IATA code, e.g. "BA", "EK").
 * Returns multiple sheds when an airline spans more than one handler.
 */
export function findByAirlineCode(airlineCode: string): MergedShed[] {
  const needle = airlineCode.trim().toUpperCase();
  if (!needle) return [];
  return DATA.sheds.filter(s =>
    s.airlines.some(a => a.code.toUpperCase() === needle),
  );
}

/**
 * Find the authoritative shed for a 3-digit AWB prefix.
 * Checks the airline_prefix_overrides table first (AA 001, ET 071, GF 072,
 * KL 074, BA 125) for the canonical answer, then falls back to a scan of
 * per-shed awb_prefixes arrays.
 */
export function findByAwbPrefix(prefix: string): {
  override?: AirlinePrefixOverride;
  sheds: MergedShed[];
} {
  const needle = prefix.trim();
  if (!needle) return { sheds: [] };
  const override = DATA.airline_prefix_overrides[needle];
  const sheds = DATA.sheds.filter(s => s.awb_prefixes.includes(needle));
  return { override, sheds };
}

/**
 * Free-text search across shed_code, subject_code, handler names, email,
 * airlines, routing_notes, HMRC code/address.
 */
export function search(query: string, limit = 50): MergedShed[] {
  const needle = query.trim().toLowerCase();
  if (!needle) return [];

  const haystack = (s: MergedShed) =>
    [
      s.key,
      s.shed_code,
      s.subject_code,
      s.handler_legal_name,
      s.handler_common_name,
      s.prealert_email,
      s.routing_notes,
      s.hmrc?.code,
      s.hmrc?.address,
      s.hmrc?.legal_name,
      ...s.airlines.flatMap(a => [a.code, a.name]),
      ...s.awb_prefixes,
    ]
      .filter(Boolean)
      .join(' ')
      .toLowerCase();

  return DATA.sheds.filter(s => haystack(s).includes(needle)).slice(0, limit);
}

/**
 * Filter sheds by confidence tier.
 */
export function filterByConfidence(confidence: Confidence): MergedShed[] {
  return DATA.sheds.filter(s => s.confidence === confidence);
}
